### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by engahmed1190** [jayanthkoushik/neural-style#2]
An issue is found related to negative value 
This is the error
```
Using Theano backend.
Traceback (most recent call last):
  File "fast_neural_style.py", line 59, in <module>
    transformer_net = get_transformer_net(X, weights)
  File "/home/Desktop/fast_neural_style/transformer_net.py", line 80, in get_transformer_net
    y = conv_layer(input_, 32, 9)
  File "/home/Desktop/fast_neural_style/transformer_net.py", line 67, in conv_layer
    out = InstanceNormalization()(out)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/home/deeplearning/fast_neural_style/transformer_net.py", line 18, in build
    self.scale = self.add_weight(shape=(input_shape[1],), initializer="uniform", trainable=True)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 418, in add_weight
    weight = initializer(shape, name=name)
  File "/usr/local/lib/python3.5/dist-packages/keras/initializations.py", line 33, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/theano_backend.py", line 188, in random_uniform_variable
    return variable(np.random.uniform(low=low, high=high, size=shape),
  File "mtrand.pyx", line 1291, in mtrand.RandomState.uniform (numpy/random/mtrand/mtrand.c:19304)
  File "mtrand.pyx", line 242, in mtrand.cont2_array_sc (numpy/random/mtrand/mtrand.c:7401)
ValueError: negative dimensions are not allowed
```

**Comment by jayanthkoushik** [comment]
Could you tell me the command you used that led to this error?

**Comment by engahmed1190** [comment]
> python fast_neural_style.py eval --content-image chicago.jpg --output-image /home/Desktop/fast-neural-style-keras/images/generated --model stained_glass.h5

**Comment by jayanthkoushik** [comment]
Make sure you use the correct version of Keras. You have to use a slightly different version. Install using `pip install --upgrade git+https://github.com/jayanthkoushik/keras.git`.

**Comment by jayanthkoushik** [comment]
And make sure other packages are up to date.

**Comment by jayanthkoushik** [comment]
Also, in your command, note that the `--output-image` argument should point to an output file, not a directory.

**Comment by engahmed1190** [comment]
I have found a link discuss this issue [https://github.com/fchollet/keras/issues/1340] , i don't know what is the cause of adding this argument to this part of the code 
```
def conv_layer(in_, nb_filter, filter_length, subsample=1, upsample=1, only_conv=False):
    if upsample != 1:
        out = UpSampling2D(size=(upsample, upsample))(in_)
    else:
        out = in_
    padding = int(np.floor(filter_length / 2))
    out = ReflectPadding2D((padding, padding))(out)
    out = Conv2D(nb_filter, filter_length, filter_length, subsample=(subsample, subsample), border_mode="valid")(out)
    if not only_conv:
        out = InstanceNormalization()(out)
        out = Activation("relu")(out)
    return out
```

replacing 
`out = Conv2D(nb_filter, filter_length, filter_length, subsample=(subsample, subsample), border_mode="valid")(out)`


by 
`out = Conv2D(nb_filter, filter_length, filter_length, subsample=(subsample, subsample), border_mode="valid",dim_ordering='th')(out)`

also, the output image file do you mean I create an empty file and remain the extension 
as 

> someImage.jpg

**Comment by jayanthkoushik** [comment]
Oh I see. Yes, it seems like your Keras configuration is not correct. Edit `~/.keras/keras.json` and make sure it contains the following:

```
{
    "dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}
```

**Comment by jayanthkoushik** [comment]
And for the output image, in the argument just put whatever name you want the output image to have. You don't have to create the file yourself. So if you have `--output-image images/generated.jpg`, then `generated.jpg` will be created. But make sure the directory `images` exists.

**Comment by engahmed1190** [comment]
Thanks, really helpful
